export const useLocale = () => {
  const locale = useState<string>('locale', () => 'fr')

  const t = (key: string) => {
    const translations: Record<string, { fr: string, en: string }> = {
      welcome_title: { fr: 'Bienvenue sur', en: 'Welcome to' },
      welcome_subtitle: {
        fr: 'Répondez à quelques questions pour évaluer votre situation et obtenir une orientation vers le niveau de soin approprié.',
        en: 'Answer a few questions to assess your situation and get guidance on the appropriate level of care.'
      },
      start_button: { fr: 'Commencer le questionnaire', en: 'Start questionnaire' },
      feature_questions: { fr: 'Questions ciblées', en: 'Targeted questions' },
      feature_questions_desc: { fr: 'Selon la zone du corps', en: 'Based on body area' },
      feature_ai: { fr: 'Analyse IA optionnelle', en: 'Optional AI analysis' },
      feature_ai_desc: { fr: 'Affinez avec Mistral AI', en: 'Refine with Mistral AI' },
      feature_rgpd: { fr: 'RGPD', en: 'GDPR' },
      feature_rgpd_desc: { fr: 'Aucune donnée stockée', en: 'No data stored' },
      feature_result: { fr: 'Résultat rapide', en: 'Quick result' },
      feature_result_desc: { fr: 'Orientation immédiate', en: 'Immediate guidance' },
      important: { fr: 'Important', en: 'Important' },
      important_text: {
        fr: 'Cette application ne fournit pas de diagnostic médical. En cas d\'urgence, appelez le 15 ou les 18.',
        en: 'This application does not provide a medical diagnosis. In case of emergency, call 15 or 18.'
      },
      select_language: { fr: 'Langue / Language', en: 'Language / Langue' },
      continue: { fr: 'Continuer', en: 'Continue' },
      analyzing: { fr: 'Analyse en cours…', en: 'Analyzing…' },
      question: { fr: 'Question', en: 'Question' },
      next: { fr: 'Suivant', en: 'Next' },
      back: { fr: 'Retour', en: 'Back' },
      low: { fr: 'Faible', en: 'Low' },
      high: { fr: 'Insupportable', en: 'Unbearable' },
      age_placeholder: { fr: 'Votre âge', en: 'Your age' },
      age_unit: { fr: 'Âge en années', en: 'Age in years' },
      recap_title: { fr: 'Vérifiez vos réponses', en: 'Check your answers' },
      recap_subtitle: {
        fr: 'Voici un résumé de vos réponses. Vous pouvez ajouter des informations supplémentaires si vous le souhaitez.',
        en: 'Here is a summary of your answers. You can add additional information if you wish.'
      },
      additional_info: { fr: 'Informations supplémentaires', en: 'Additional information' },
      additional_info_placeholder: {
        fr: 'Ajoutez tout symptôme supplémentaire, détaillez un contexte particulier ou toute information que vous souhaitez mentionner...',
        en: 'Add any additional symptoms, detail a particular context or any information you wish to mention...'
      },
      analyze_with_ai: { fr: 'Analyser avec l\'IA', en: 'Analyze with AI' },
      get_result_directly: { fr: 'Obtenir mon résultat directement', en: 'Get my result directly' },
      ai_analysis_title: { fr: 'Affinage IA', en: 'AI Refinement' },
      ai_analysis_subtitle: {
        fr: 'Voici un résumé de vos réponses. Ajoutez des informations complémentaires pour affiner l\'analyse.',
        en: 'Here is a summary of your answers. Add complementary information to refine the analysis.'
      },
      analyze: { fr: 'Analyser', en: 'Analyze' },
      continue_to_result: { fr: 'Continuer vers le résultat', en: 'Continue to result' },
      skip_step: { fr: 'Passer cette étape', en: 'Skip this step' },
      loading_text_ai: { fr: 'Envoi au backend · Analyse IA · Calcul du triage…', en: 'Sending to backend · AI analysis · Calculating triage...' },
      loading_text_rules: { fr: 'Calcul par règles…', en: 'Calculating by rules...' },
      loading_offline: { fr: 'Mode hors-ligne · Calcul par règles…', en: 'Offline mode · Calculating by rules...' },
      ai_warning_title: { fr: 'Analyse par intelligence artificielle', en: 'Artificial intelligence analysis' },
      ai_warning_text: {
        fr: 'Les résultats ci-dessous proviennent d\'un modèle d\'IA et ne constituent pas un diagnostic médical fiable. Toute information générée doit être vérifiée par un professionnel de santé.',
        en: 'The results below come from an AI model and do not constitute reliable medical diagnosis. Any generated information must be verified by a healthcare professional.'
      },
      ai_consent: { fr: 'Je comprends que ces informations sont générées par IA et ne remplacent pas un avis médical', en: 'I understand that this information is generated by AI and does not replace medical advice' },
      entities_detected: { fr: 'Entités médicales détectées', en: 'Medical entities detected' },
      result_title: { fr: 'Votre orientation', en: 'Your guidance' },
      result_urgency: { fr: 'Urgence', en: 'Emergency' },
      result_rapide: { fr: 'Consultation rapide', en: 'Quick consultation' },
      result_standard: { fr: 'Consultation standard', en: 'Standard consultation' },
      result_summary_urgency: { fr: 'Consultez aux urgences sans attendre ou appelez le 15.', en: 'Consult the emergency department immediately or call 15.' },
      result_summary_rapide: { fr: 'Consultez un médecin dans les 24 à 48 heures.', en: 'Consult a doctor within 24 to 48 hours.' },
      result_summary_standard: { fr: 'Prenez rendez-vous avec votre médecin dans les prochains jours.', en: 'Make an appointment with your doctor in the coming days.' },
      pistes_exploration: { fr: 'Pistes à explorer avec votre médecin', en: 'Possible causes to explore with your doctor' },
      flags_detected: { fr: 'Facteurs identifiés', en: 'Factors identified' },
      restart: { fr: 'Recommencer', en: 'Start over' },
    }
    return translations[key]?.[locale.value] || key
  }

  return { locale, t }
}